export default {
  TYPES: {
    TV: "television",
    LAMP: "lamp",
    FRIDGE: "fridge",
    OVEN: "oven",
    WATCH: "watch",
    AIR_CONDITIONER: "air-Conditioner",
    STOVE: "stove",
  },
  IMAGES: {
    television: require("../../assets/TV.jpg"),
    lamp: require("../../assets/lamp.jpg"),
    fridge: require("../../assets/fridge.jpg"),
    oven: require("../../assets/oven.jpg"),
    watch: require("../../assets/watch.jpg"),
    airConditioner: require("../../assets/airConditioner.png"),
    stove: require("../../assets/stove.jpg"),
    plus: require("../../assets/plus.jpg"),
  },
  INDEXTYPES: {
    1: "television",
    2: "lamp",
    3: "fridge",
    4: "oven",
    5: "watch",
    6: "air-Conditioner",
    7: "stove",
  },
};
